# Generated by Django 4.1.3 on 2022-11-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='code',
            field=models.CharField(default='XX-XX:XXXX', max_length=101),
        ),
    ]
