# Generated by Django 4.1.3 on 2022-11-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maint', '0002_alter_work_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='code',
            field=models.CharField(default='XX-XX:XXXX', max_length=101, unique=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
